name: Release
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci && npm i -g @vscode/vsce semantic-release
      - run: npm run release
        if: success()
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
