name: release
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i -g @vscode/vsce
        env:
          CI: true
      - run: npm run release
        if: success()
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

